### ISSUE TITLE
Use Docker container for lambda dependencies instead of each lambda

### ISSUE THREAD

**Issue by jterry64** [wri/gfw-user-aoi-batch#12]
**Is your feature request related to a problem? Please describe.**
Currently we're building a docker image for each lambda to get the package file. For five lambdas, this takes just too long and makes deploying development very slow. 

**Describe the solution you'd like**
We can take advantage of lambda layers for dependencies, and keep the actual lambda functions as lightweight as possible: https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html

I already started using that for raster analysis service since building the GDAL image and NumPy/Rasterio dependencies took so long. This allows to just put all dependencies separately, and then deployment of changes to the lambda function can be quickly done on top of that.

**Comment by thomas-maschler** [comment]
This is a nice concept. We should place the layers into the core repo, so that we can reuse them easily.

For deploying the lambda function itself, we can then use the `archive_file` provider as in Hectors code example. It does the zipping for you. https://github.com/wri/gfw-iac-workshop/blob/master/terraform/archive.tf

**Comment by thomas-maschler** [comment]
How will you test that all the required dependencies are available inside the lambda? Can you do that already before deploying it using the aws mocking environment? Or do you need to deploy it to AWS first and run some end to end test on the actual function?
